#+TITLE: Linux adminování - jak si rozjet u sebe

S následující konfigurací se pokusíme co nejméně ovlivnit konfigurace, které už
na počítači máte. Vůbec tedy nevadí, pokud máte už fungující konfiguraci emacsu,
nebudeme na ni sahat.

* Instalace Spacemacsu
Vytvoříme si adresář pro testy s názvem =spacemacs= a v něm nainstalujeme emacs.
Pro jistotu zkontrolujeme přítomnost =.emacs.d= v test adresáři, kdybychom
náhodou pustili znovu.

#+BEGIN_SRC sh
mkdir -p ~/spacemacs
[[ -d "~/spacemacs/.emacs.d" ]] && mv ~/spacemacs/.emacs.d ~/spacemacs/emacs.d-backup
git clone --single-branch -b develop https://github.com/syl20bnr/spacemacs ~/spacemacs/.emacs.d
#+END_SRC

* Spuštění Spacemacsu
#+BEGIN_SRC sh
HOME=~/spacemacs emacs
#+END_SRC

Já si přidávám alias 

#+BEGIN_SRC sh
alias testmacs='HOME=~/spacemacs emacs'
#+END_SRC

A následně pustím jako =testmacs=

** První spuštění

Při prvním spuštění se vás zeptá na otázky:
- /What is your preferred editing style?/ :: *vim*
- /What distribution of spacemacs would you like to start with?/ :: *spacemacs*
               
Pro testování si upravte nastavení cesty k vrstvám, konfiguraci otevřete už ze /spacemacs/ přes zkratku ~SPC f e d~.

#+BEGIN_SRC elisp
dotspacemacs-configuration-layer-path '("~/spacemacs/.spacemacs.d/layers/")
#+END_SRC

** Přidání igloonet-defaults
Pro pohodlnou práci si, alespoň v této testovací verzi, přidejte vrstvu [[https://github.com/igloonet/igloonet-defaults][igloonet-defaults]]. Jak na to se dočtete v jejím README.
